server:
  port: 8050
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          username: expertsconseil
          password: MaherFormation2025
          uri: https://github.com/expertsconseil/application-config.git

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always




